### ISSUE TITLE
Segment Anything for Nuke

### ISSUE THREAD

**Issue by aldmbmtl** [juno-fx/Terra-Official-Plugins#12]
https://github.com/rafaelperez/Segment-Anything-for-Nuke

**Comment by aldmbmtl** [comment]
@lamepennies this is going to take a little bit of fighting since it looks like you need to compile the model during install.

**Comment by lamepennies** [comment]
You don't need to compile it. Just dl and put in the cattery folder.

**Comment by aldmbmtl** [comment]
We don't have a default location for cattery stuff. We also don't want to store it in the users .nuke directory since everyone's is different. I will look into it once we get back from siggraph

**Comment by skeleturtle** [comment]
Sounds like something for Terra, and maybe we can set some env variable during the install that tracks the location so jfx-nuke knows where to look?

**Comment by aldmbmtl** [comment]
This is on the plugins repo. This is probably something we can store on the plugin and then jfx-nuke can just ask terra where it is.

**Comment by skeleturtle** [comment]
It would be on the user to ensure they choose the same cattery location for new plugins for it, but that's on them

**Comment by aldmbmtl** [comment]
Added this here

https://github.com/juno-fx/Terra-Official-Plugins/issues/16

**Comment by ddesmond** [comment]
We should install Cattery models under /apps/nuke/cattery, then its easy to provide support for nuke loading this model either:
trough env var, .nuke setup, pipeline file, workstation boot
Ill setup the plugin and close the double tickets.

**Comment by aldmbmtl** [comment]
Sounds good to me :)

**Comment by ddesmond** [comment]
Triplicates (or kinda related):
https://github.com/juno-fx/Terra-Official-Plugins/issues/39
https://github.com/juno-fx/Terra-Official-Plugins/issues/16
https://github.com/juno-fx/Terra-Official-Plugins/issues/12

I will leave just the 39 open, since that encompases all models available or listed from Foundry site.
