### ISSUE TITLE
starter template plugin needed

### ISSUE THREAD

**Issue by skeleturtle** [juno-fx/Terra-Official-Plugins#13]
Providing a "blank" starter template plugin for users to use would be a nice addition.

**Comment by aldmbmtl** [comment]
@ddesmond actually just made something for this. It is a make command. Just needs documentation.

**Comment by ddesmond** [comment]
That would be called then - Terra application plugin template.

Yes, i do: make app-demoapp, and basic plugin structure gets created so i can jump and work on it, instead copy pastin, renaming variables etc.. some manual work is required, some of those can be improved for sure.

Let me clean up and make docs, the branch is already live

**Comment by ddesmond** [comment]
Docs updated in separate branch.
We can officaly merge this.
