### ISSUE TITLE
Add / Setup Cattery plugins for Nuke to Terra

### ISSUE THREAD

**Issue by skeleturtle** [juno-fx/Terra-Official-Plugins#39]

**Comment by ddesmond** [comment]
https://www.foundry.com/insights/machine-learning/the-artists-guide-to-cattery?_gl=1*1g741ne*_gcl_au*MTI5NTY2MDc4My4xNzE3NzcwMjU0*_ga*MTE5NTYwMTMyNy4xNzE3NzcwMjUy*_ga_QQ35L7EVY0*MTcyMzQ2Njc3OS45LjEuMTcyMzQ2Njg4Ny4wLjAuMA..*_ga_THF8SPBJQF*MTcyMzQ2Njc3OS45LjEuMTcyMzQ2Njg4Ni4wLjAuMA..

**Comment by ddesmond** [comment]
Related tickets (closed):

https://github.com/juno-fx/Terra-Official-Plugins/issues/16
https://github.com/juno-fx/Terra-Official-Plugins/issues/12

I will leave just the 39 open, since that encompases all models available or listed from Foundry site.

**Comment by ddesmond** [comment]
Foundry says:

Install
Nuke 15 series

Download and unzip the package

Copy the extracted Cattery folder to your .nuke folder or your preferred location (if you choose your own location, make sure to add the path to your NUKE_PATH)
