### ISSUE TITLE
Rocket Chat Desktop App Electron

### ISSUE THREAD

**Issue by skeleturtle** [juno-fx/Terra-Official-Plugins#64]
please get us the rocket chat desktop app. 

Here is the repo:
https://github.com/RocketChat/Rocket.Chat.Electron

**Comment by ddesmond** [comment]
Reopening this for dev.

**Comment by ddesmond** [comment]
https://docs.rocket.chat/v1/docs/deploy-with-kubernetes#configuration

**Comment by aldmbmtl** [comment]
Is this still needed?

**Comment by ddesmond** [comment]
We can close this for now and reopen when needed.
