### ISSUE TITLE
Requested Deep Nodes

### ISSUE THREAD

**Issue by aldmbmtl** [juno-fx/Terra-Official-Plugins#71]
Hello,
For later when we are using deep, these open source tools are good

https://github.com/charlesangus/DeepC

**Comment by ddesmond** [comment]
These are compiled for Nuke versions lower than we are using (15).
https://github.com/charlesangus/DeepC/releases/tag/v0.5.6

Do we want to try these if they work or do we want to compile the whole set again?

**Comment by lamepennies** [comment]
We should put in an issue on his repo because he made some fixes for 14 and people have commented. Unless you want to compile them. Whatever is easier. I think this is low prio. I doubt we'll be doing any deep stuff anytime soon.

**Comment by ddesmond** [comment]
We can close this for now. Tackle it after we have some deep outputs we rendered to test with.
