### ISSUE TITLE
Add Project folder to Mr2V favorites automaticaly

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/Terra-Official-Plugins#85]
Be awesome to have the show or other show defaults for the mr2v favorites by default

**Comment by ddesmond** [comment]
as for this commits, MRV2 seeds it settings from within polaris, since they go to user config folder (should be moved here)
There is a place where we can setup shortcuts and we could do it when we install it in the cluster. 
We just need a way to pickup the project name and fill it in! :)

**Comment by ddesmond** [comment]
Tracking user config move files issue https://github.com/juno-fx/polaris/issues/222

**Comment by ddesmond** [comment]
We can close this for now. Tackle this after DMO cleanups.
