### ISSUE TITLE
Add MR2V in "Send To" right click action

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/Terra-Official-Plugins#86]
It'd be great to add mr2v to the send to action button so you can launch files easier.

**Comment by ddesmond** [comment]
Ive tried a simple setup which didint work out, will check more the XFCE docs and see how we could add this from within the app installer itself.

Not a prio thou ....

**Comment by ddesmond** [comment]
We can close this for now. Tackle this after DMO cleanups.
