### ISSUE TITLE
SSH Port Forward Deployment

### ISSUE THREAD

**Issue by aldmbmtl** [juno-fx/Terra-Official-Plugins#92]
We should provide a plugin that will take an ssh key and a port. Then it will deploy pod to Kubernetes that will use that information to ssh into the remote server and port forward it. Then present that as a service.

The idea is to allow for users to connect remote out of cluster resources to the cluster and present them as a service.

For example, user services like private wikis, VPN's and most importantly port forwarding license servers. Into the cluster.

Juno would like to switch to this approach so it can remove the need for the very expensive AWS Global Network with multiple transit gateways.

**Comment by aldmbmtl** [comment]
@ddesmond this is becoming a much higher priority since we need this working to fix our license server.

**Comment by ddesmond** [comment]
Ol Jumpo Box! :)

**Comment by ddesmond** [comment]
Jumpo added to Plugins and merged to main.
please check it if this is what we want :)
