### ISSUE TITLE
Lens distortion plugin pack

### ISSUE THREAD

**Issue by skeleturtle** [juno-fx/Terra-Official-Plugins#98]
https://www.3dequalizer.com/?site=tech_docs&id=110216_01

We probably will want to ensure we have a way to install the LDPK plugins for 3DE nuke distortion nodes. Link above is latest version, I'm not sure if we would need the older versions or not to be completely honest. 

Once installed I can setup jfx-nuke to load proper compiled versions based on the nuke version that's launching. So long as I can easily grab the path to where it's been installed.

**Comment by ddesmond** [comment]
added in https://github.com/juno-fx/Terra-Official-Plugins/commit/d1136d6cbddc47ebd411389753b6d7fa23499165

will be merged to main once we merge to main

**Comment by skeleturtle** [comment]
@ddesmond thank you!

**Comment by ddesmond** [comment]
Merge in main, closing, please test once deployed :)
